apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-webapi-deployment
spec:
  selector:
    matchLabels:
      app: hello-webapi-pod
  template:
    metadata:
      labels:
        app: hello-webapi-pod
    spec:
      containers:
      - name: hello-webapi-container
        image: hello-webapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
